### ejemplo POST, se crea un nuevo registro de datos del sensor
curl -X POST http://localhost:5000/api/sensor-data \
-H "Content-Type: application/json" \
-d '{
    "sensor_id": 1,
    "timestamp": "2024-06-15T14:30:00",
    "temperatura": 25.5,
    "presion": 1013.25,
    "humedad": 45.0
}'

### Consultar todos los datos
curl -X GET "http://localhost:5000/api/sensor-data"

### Consultar un sensor específico (id=1)
curl -X GET "http://localhost:5000/api/sensor-data?sensor_id=1"

### Consultar datos de un sensor en un rango de tiempo
curl "http://localhost:5000/api/sensor-data?start_time=2025-06-17T00:00:00&end_time=2025-06-18T23:59:59"

###
curl http://localhost:5000/api/health
